library(ggplot2)
library(reshape2)

data1 = read.table("./bloom_lookup_measurements", sep = "\t", col.names = c("FIB-SIZE", "TIME"), fill = F, strip.white = F)
data2 = read.table("./radix_lookup_measurements", sep = "\t", col.names = c("FIB-SIZE", "TIME"), fill = F, strip.white = F)
df1 = as.data.frame(data1)
df2 = as.data.frame(data2)
fval1 = aggregate(df1$TIME ~ df1$FIB.SIZE, df1, mean)
fval2 = aggregate(df2$TIME ~ df2$FIB.SIZE, df2, mean)
colnames(fval1) <- c("FIB", "TIME")
colnames(fval2) <- c("FIB", "TIME")
fval <- cbind(fval1, fval2$TIME)
colnames(fval) <- c("FIB", "Bloom", "Radix")
fval.m <- melt(fval,id.vars='FIB', measure.vars=c('Bloom','Radix'))

tiff("lookup.tif", units="in", width=11, height=8.5, res=300)
ggplot() + geom_boxplot(data= fval.m, aes(x=factor(FIB), y=value, color=variable, outlier.shape = NA), varwidth = F, size = 2.0) + xlab("FIB Size") + ylab("Average Time (in nanosec)") + ggtitle("Lookup Performance for XID IDs") + labs(colour = "Algorithms")
dev.off()

data1 = read.table("./bloom_nexthops_measurements", sep = "\t", col.names = c("NEXTHOPS", "TIME"), fill = F, strip.white = F)
data2 = read.table("./radix_nexthops_measurements", sep = "\t", col.names = c("NEXTHOPS", "TIME"), fill = F, strip.white = F)
df1 = as.data.frame(data1)
df2 = as.data.frame(data2)
fval1 = aggregate(df1$TIME ~ df1$NEXTHOPS, df1, mean)
fval2 = aggregate(df2$TIME ~ df2$NEXTHOPS, df2, mean)
colnames(fval1) <- c("NEXTHOPS", "TIME")
colnames(fval2) <- c("NEXTHOPS", "TIME")
fval <- cbind(fval1, fval2$TIME)
colnames(fval) <- c("FIB", "Bloom", "Radix")
fval.m <- melt(fval,id.vars='FIB', measure.vars=c('Bloom','Radix'))

tiff("nexthops.tif", units="in", width=11, height=8.5, res=300)
ggplot() + geom_boxplot(data= fval.m, aes(x=factor(FIB), y=value, color=variable, outlier.shape = NA), varwidth = F, size = 2.0) + xlab("Number of Nexthops") + ylab("Average Time (in nanosec)") + ggtitle("Lookup Performance for XID IDs") + labs(colour = "Algorithms")
dev.off()